{
 "title": "gRPC Сервис Метрики",
 "tags": [
  "grpc",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Общее количество пользователей",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "grpc_users_total" }
   ]
  },
  {
   "title": "Количество gRPC запросов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(grpc_requests_total)" }
   ]
  },
  {
   "title": "Запросы по методам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "rate(grpc_requests_total[1m])", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Длительность запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(grpc_request_duration_seconds_bucket[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, rate(grpc_request_duration_seconds_bucket[1m]))",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}