apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-grpc-app.fullname" . }}-http-gateway
  labels:
    {{- include "k8s-grpc-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-grpc-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http-gateway
  template:
    metadata:
      labels:
        {{- include "k8s-grpc-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: "{{ .Values.httpGateway.image.repository }}:{{ .Values.httpGateway.image.tag }}"
        imagePullPolicy: {{ .Values.httpGateway.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: GRPC_SERVER_ADDR
          value: "{{ include "k8s-grpc-app.fullname" . }}-grpc-server:8080"
        - name: GRAYLOG_ADDR
          value: "{{ include "k8s-grpc-app.fullname" . }}-graylog:12201"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.httpGateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-grpc-app.fullname" . }}-http-gateway
  labels:
    {{- include "k8s-grpc-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-gateway
spec:
  ports:
  - name: http
    port: {{ .Values.httpGateway.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "k8s-grpc-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http-gateway 