apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-grpc-app.fullname" . }}-web-app
  labels:
    app: {{ include "k8s-grpc-app.name" . }}-web-app
    chart: {{ include "k8s-grpc-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "k8s-grpc-app.name" . }}-web-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-grpc-app.name" . }}-web-app
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webApp.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-grpc-app.fullname" . }}-web-app
  labels:
    app: {{ include "k8s-grpc-app.name" . }}-web-app
    chart: {{ include "k8s-grpc-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.webApp.service.type }}
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "k8s-grpc-app.name" . }}-web-app
    release: {{ .Release.Name }} 